language: node_js
node_js:
    - "8"
    - "10"

branches:
    only:
        - master
        - /^greenkeeper/.*$/

before_script:
    - npm install -g firebase-tools
    - npm install -g @angular/cli

script:
    - ng build --prod --aot

after_success:
    - firebase deploy --token "$FIREBASE_TOKEN"